[package]
name = "sql-formatter"
version = "0.1.1"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
onig = { version = "6.4.0", default-features = false }

[dependencies.regex]
version = "1.10.5"
default-features = false
features = ["std"]

[profile.release]
strip = true
